markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
title: Start with K
email: katrinashui2023@gmail.com
description:
  en: Sharing a journey code starting from zero 
  ch: 分享從零度開始的編碼經歷
baseurl: ""
url: ""


# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag


# Multilingual settings
languages: ["en", "ch"]
default_lang: "en"
exclude_from_localization: ["assets"]

collections:
  enPosts:
    output: true
    permalink: /en/post/:name
  enGlossary:
    output: true
    permalink: /en/glossary/:name
collections_dir: en

defaults:
  - scope:
      path: "en/_enPosts"
      type: posts
    values:
      layout: posts
  - scope:
      path: "en/_enGlossary"
    values:
      layout: default

      