name: Copy Site File to another repo
run-name: Pushing new Jekyll Code
on: 
  push:
    branches:
      - main

jobs:
  copy_site_folder_to_another_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this project
        uses: actions/checkout@v4
      - name: Check out another repo project
        uses: actions/checkout@v4
        with:
          repository: Katrinasms/katrina.sh_site
          path: _site
          token: ${{ secrets.KATRINA_SH_SITE }}
      - name: Build the site in the jekyll/builder container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
      - name: Run the Script
        run: |
          chmod +x ./scripts/commit.sh
          ./scripts/commit.sh
      - name: Run the Script
        run: |
          chmod +x ./scripts/pullInServer.sh
          ./scripts/pullInServer.sh
        env: 
          SSH_PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
      - run: echo "🍏 Both File is successfully check!"

